# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AD_Decision.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1400, 899)
        Form.setStyleSheet(_fromUtf8(""))
        self.verticalLayout_7 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_period = QtGui.QLabel(Form)
        self.label_period.setObjectName(_fromUtf8("label_period"))
        self.horizontalLayout.addWidget(self.label_period)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_history = QtGui.QPushButton(Form)
        self.pushButton_history.setObjectName(_fromUtf8("pushButton_history"))
        self.horizontalLayout.addWidget(self.pushButton_history)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem2 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem2)
        self.textEdit_explication = QtGui.QTextEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_explication.sizePolicy().hasHeightForWidth())
        self.textEdit_explication.setSizePolicy(sizePolicy)
        self.textEdit_explication.setMaximumSize(QtCore.QSize(1000, 100))
        self.textEdit_explication.setStyleSheet(_fromUtf8(""))
        self.textEdit_explication.setObjectName(_fromUtf8("textEdit_explication"))
        self.horizontalLayout_17.addWidget(self.textEdit_explication)
        spacerItem3 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_txt_timer = QtGui.QLabel(Form)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(165, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.label_txt_timer.setPalette(palette)
        self.label_txt_timer.setStyleSheet(_fromUtf8("font-weight: bold;\n"
"color: brown;"))
        self.label_txt_timer.setObjectName(_fromUtf8("label_txt_timer"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_txt_timer)
        self.label_timer = QtGui.QLabel(Form)
        self.label_timer.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_timer.setStyleSheet(_fromUtf8("font-weight: bold;\n"
"color: brown;"))
        self.label_timer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_timer.setObjectName(_fromUtf8("label_timer"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_timer)
        self.label_txt_portefeuille = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_txt_portefeuille.setFont(font)
        self.label_txt_portefeuille.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_txt_portefeuille.setObjectName(_fromUtf8("label_txt_portefeuille"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_txt_portefeuille)
        self.label_portefeuille = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_portefeuille.setFont(font)
        self.label_portefeuille.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_portefeuille.setObjectName(_fromUtf8("label_portefeuille"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_portefeuille)
        self.label_txt_revenu_pile = QtGui.QLabel(Form)
        self.label_txt_revenu_pile.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_txt_revenu_pile.setObjectName(_fromUtf8("label_txt_revenu_pile"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_txt_revenu_pile)
        self.label_revenu_pile = QtGui.QLabel(Form)
        self.label_revenu_pile.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_revenu_pile.setObjectName(_fromUtf8("label_revenu_pile"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_revenu_pile)
        self.label_txt_revenu_face = QtGui.QLabel(Form)
        self.label_txt_revenu_face.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_txt_revenu_face.setObjectName(_fromUtf8("label_txt_revenu_face"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_txt_revenu_face)
        self.label_revenu_face = QtGui.QLabel(Form)
        self.label_revenu_face.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_revenu_face.setObjectName(_fromUtf8("label_revenu_face"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.label_revenu_face)
        self.horizontalLayout_2.addLayout(self.formLayout)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem7)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_txt_pile = QtGui.QLabel(Form)
        self.label_txt_pile.setObjectName(_fromUtf8("label_txt_pile"))
        self.horizontalLayout_11.addWidget(self.label_txt_pile)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_txt_pile_offre_achat = QtGui.QLabel(Form)
        self.label_txt_pile_offre_achat.setObjectName(_fromUtf8("label_txt_pile_offre_achat"))
        self.verticalLayout.addWidget(self.label_txt_pile_offre_achat)
        self.listWidget_pile_offre_achat = QtGui.QListWidget(Form)
        self.listWidget_pile_offre_achat.setObjectName(_fromUtf8("listWidget_pile_offre_achat"))
        self.verticalLayout.addWidget(self.listWidget_pile_offre_achat)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_txt_pile_offre_achat_prix = QtGui.QLabel(Form)
        self.label_txt_pile_offre_achat_prix.setObjectName(_fromUtf8("label_txt_pile_offre_achat_prix"))
        self.horizontalLayout_3.addWidget(self.label_txt_pile_offre_achat_prix)
        self.doubleSpinBox_pile_offre_achat = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBox_pile_offre_achat.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_pile_offre_achat.setObjectName(_fromUtf8("doubleSpinBox_pile_offre_achat"))
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_pile_offre_achat)
        self.pushButton_pile_offre_achat_envoyer = QtGui.QPushButton(Form)
        self.pushButton_pile_offre_achat_envoyer.setObjectName(_fromUtf8("pushButton_pile_offre_achat_envoyer"))
        self.horizontalLayout_3.addWidget(self.pushButton_pile_offre_achat_envoyer)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton_pile_offre_achat_accepter = QtGui.QPushButton(Form)
        self.pushButton_pile_offre_achat_accepter.setObjectName(_fromUtf8("pushButton_pile_offre_achat_accepter"))
        self.horizontalLayout_4.addWidget(self.pushButton_pile_offre_achat_accepter)
        self.pushButton_pile_offre_achat_supprimer = QtGui.QPushButton(Form)
        self.pushButton_pile_offre_achat_supprimer.setObjectName(_fromUtf8("pushButton_pile_offre_achat_supprimer"))
        self.horizontalLayout_4.addWidget(self.pushButton_pile_offre_achat_supprimer)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_13.addLayout(self.verticalLayout)
        spacerItem9 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem9)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_txt_pile_offre_vente = QtGui.QLabel(Form)
        self.label_txt_pile_offre_vente.setObjectName(_fromUtf8("label_txt_pile_offre_vente"))
        self.verticalLayout_3.addWidget(self.label_txt_pile_offre_vente)
        self.listWidget_pile_offre_vente = QtGui.QListWidget(Form)
        self.listWidget_pile_offre_vente.setObjectName(_fromUtf8("listWidget_pile_offre_vente"))
        self.verticalLayout_3.addWidget(self.listWidget_pile_offre_vente)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_txt_pile_offre_vente_prix = QtGui.QLabel(Form)
        self.label_txt_pile_offre_vente_prix.setObjectName(_fromUtf8("label_txt_pile_offre_vente_prix"))
        self.horizontalLayout_7.addWidget(self.label_txt_pile_offre_vente_prix)
        self.doubleSpinBox_pile_offre_vente = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBox_pile_offre_vente.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_pile_offre_vente.setObjectName(_fromUtf8("doubleSpinBox_pile_offre_vente"))
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_pile_offre_vente)
        self.pushButton_pile_offre_vente_envoyer = QtGui.QPushButton(Form)
        self.pushButton_pile_offre_vente_envoyer.setObjectName(_fromUtf8("pushButton_pile_offre_vente_envoyer"))
        self.horizontalLayout_7.addWidget(self.pushButton_pile_offre_vente_envoyer)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pushButton_pile_offre_vente_accepter = QtGui.QPushButton(Form)
        self.pushButton_pile_offre_vente_accepter.setObjectName(_fromUtf8("pushButton_pile_offre_vente_accepter"))
        self.horizontalLayout_8.addWidget(self.pushButton_pile_offre_vente_accepter)
        self.pushButton_pile_offre_vente_supprimer = QtGui.QPushButton(Form)
        self.pushButton_pile_offre_vente_supprimer.setObjectName(_fromUtf8("pushButton_pile_offre_vente_supprimer"))
        self.horizontalLayout_8.addWidget(self.pushButton_pile_offre_vente_supprimer)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_13.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.label_pile_txt_transactions = QtGui.QLabel(Form)
        self.label_pile_txt_transactions.setObjectName(_fromUtf8("label_pile_txt_transactions"))
        self.verticalLayout_5.addWidget(self.label_pile_txt_transactions)
        self.listWidget_pile_transactions = QtGui.QListWidget(Form)
        self.listWidget_pile_transactions.setObjectName(_fromUtf8("listWidget_pile_transactions"))
        self.verticalLayout_5.addWidget(self.listWidget_pile_transactions)
        self.horizontalLayout_15.addLayout(self.verticalLayout_5)
        spacerItem10 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem10)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_txt_face = QtGui.QLabel(Form)
        self.label_txt_face.setObjectName(_fromUtf8("label_txt_face"))
        self.horizontalLayout_12.addWidget(self.label_txt_face)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_txt_face_offre_achat = QtGui.QLabel(Form)
        self.label_txt_face_offre_achat.setObjectName(_fromUtf8("label_txt_face_offre_achat"))
        self.verticalLayout_2.addWidget(self.label_txt_face_offre_achat)
        self.listWidget_face_offre_achat = QtGui.QListWidget(Form)
        self.listWidget_face_offre_achat.setObjectName(_fromUtf8("listWidget_face_offre_achat"))
        self.verticalLayout_2.addWidget(self.listWidget_face_offre_achat)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_txt_face_offre_achat_prix = QtGui.QLabel(Form)
        self.label_txt_face_offre_achat_prix.setObjectName(_fromUtf8("label_txt_face_offre_achat_prix"))
        self.horizontalLayout_5.addWidget(self.label_txt_face_offre_achat_prix)
        self.doubleSpinBox_face_offre_achat = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBox_face_offre_achat.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_face_offre_achat.setObjectName(_fromUtf8("doubleSpinBox_face_offre_achat"))
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_face_offre_achat)
        self.pushButton_face_offre_achat_envoyer = QtGui.QPushButton(Form)
        self.pushButton_face_offre_achat_envoyer.setObjectName(_fromUtf8("pushButton_face_offre_achat_envoyer"))
        self.horizontalLayout_5.addWidget(self.pushButton_face_offre_achat_envoyer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton_face_offre_achat_accepter = QtGui.QPushButton(Form)
        self.pushButton_face_offre_achat_accepter.setObjectName(_fromUtf8("pushButton_face_offre_achat_accepter"))
        self.horizontalLayout_6.addWidget(self.pushButton_face_offre_achat_accepter)
        self.pushButton_face_offre_achat_supprimer = QtGui.QPushButton(Form)
        self.pushButton_face_offre_achat_supprimer.setObjectName(_fromUtf8("pushButton_face_offre_achat_supprimer"))
        self.horizontalLayout_6.addWidget(self.pushButton_face_offre_achat_supprimer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_14.addLayout(self.verticalLayout_2)
        spacerItem12 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem12)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_txt_face_offre_vente = QtGui.QLabel(Form)
        self.label_txt_face_offre_vente.setObjectName(_fromUtf8("label_txt_face_offre_vente"))
        self.verticalLayout_4.addWidget(self.label_txt_face_offre_vente)
        self.listWidget_face_offre_vente = QtGui.QListWidget(Form)
        self.listWidget_face_offre_vente.setObjectName(_fromUtf8("listWidget_face_offre_vente"))
        self.verticalLayout_4.addWidget(self.listWidget_face_offre_vente)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_txt_face_offre_vente_prix = QtGui.QLabel(Form)
        self.label_txt_face_offre_vente_prix.setObjectName(_fromUtf8("label_txt_face_offre_vente_prix"))
        self.horizontalLayout_9.addWidget(self.label_txt_face_offre_vente_prix)
        self.doubleSpinBox_face_offre_vente = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBox_face_offre_vente.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_face_offre_vente.setObjectName(_fromUtf8("doubleSpinBox_face_offre_vente"))
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_face_offre_vente)
        self.pushButton_face_offre_vente_envoyer = QtGui.QPushButton(Form)
        self.pushButton_face_offre_vente_envoyer.setObjectName(_fromUtf8("pushButton_face_offre_vente_envoyer"))
        self.horizontalLayout_9.addWidget(self.pushButton_face_offre_vente_envoyer)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.pushButton_face_offre_vente_accepter = QtGui.QPushButton(Form)
        self.pushButton_face_offre_vente_accepter.setObjectName(_fromUtf8("pushButton_face_offre_vente_accepter"))
        self.horizontalLayout_10.addWidget(self.pushButton_face_offre_vente_accepter)
        self.pushButton_face_offre_vente_supprimer = QtGui.QPushButton(Form)
        self.pushButton_face_offre_vente_supprimer.setObjectName(_fromUtf8("pushButton_face_offre_vente_supprimer"))
        self.horizontalLayout_10.addWidget(self.pushButton_face_offre_vente_supprimer)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_14.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.label_face_txt_transactions = QtGui.QLabel(Form)
        self.label_face_txt_transactions.setObjectName(_fromUtf8("label_face_txt_transactions"))
        self.verticalLayout_6.addWidget(self.label_face_txt_transactions)
        self.listWidget_face_transactions = QtGui.QListWidget(Form)
        self.listWidget_face_transactions.setObjectName(_fromUtf8("listWidget_face_transactions"))
        self.verticalLayout_6.addWidget(self.listWidget_face_transactions)
        self.horizontalLayout_15.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        spacerItem13 = QtGui.QSpacerItem(20, 55, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem13)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_period.setText(_translate("Form", "Période 1", None))
        self.pushButton_history.setText(_translate("Form", "Historique", None))
        self.label_txt_timer.setText(_translate("Form", "Temps restant:", None))
        self.label_timer.setText(_translate("Form", "00:05:00", None))
        self.label_txt_portefeuille.setText(_translate("Form", "Valeur du portefeuille:", None))
        self.label_portefeuille.setText(_translate("Form", "50.00€", None))
        self.label_txt_revenu_pile.setText(_translate("Form", "Etat du monde Pile:", None))
        self.label_revenu_pile.setText(_translate("Form", "25.50€", None))
        self.label_txt_revenu_face.setText(_translate("Form", "Etat du monde Face:", None))
        self.label_revenu_face.setText(_translate("Form", "10.00€", None))
        self.label_txt_pile.setText(_translate("Form", "Pile", None))
        self.label_txt_pile_offre_achat.setText(_translate("Form", "Offres d\'achat", None))
        self.label_txt_pile_offre_achat_prix.setText(_translate("Form", "Faire une offre", None))
        self.pushButton_pile_offre_achat_envoyer.setText(_translate("Form", "Envoyer", None))
        self.pushButton_pile_offre_achat_accepter.setText(_translate("Form", "Accepter l\'offre", None))
        self.pushButton_pile_offre_achat_supprimer.setText(_translate("Form", "Supprimer mon offre", None))
        self.label_txt_pile_offre_vente.setText(_translate("Form", "Offres de vente", None))
        self.label_txt_pile_offre_vente_prix.setText(_translate("Form", "Faire une offre", None))
        self.pushButton_pile_offre_vente_envoyer.setText(_translate("Form", "Envoyer", None))
        self.pushButton_pile_offre_vente_accepter.setText(_translate("Form", "Accepter l\'offre", None))
        self.pushButton_pile_offre_vente_supprimer.setText(_translate("Form", "Supprimer mon offre", None))
        self.label_pile_txt_transactions.setText(_translate("Form", "Transactions", None))
        self.label_txt_face.setText(_translate("Form", "Face", None))
        self.label_txt_face_offre_achat.setText(_translate("Form", "Offres d\'achat", None))
        self.label_txt_face_offre_achat_prix.setText(_translate("Form", "Faire une offre", None))
        self.pushButton_face_offre_achat_envoyer.setText(_translate("Form", "Envoyer", None))
        self.pushButton_face_offre_achat_accepter.setText(_translate("Form", "Accepter l\'offre", None))
        self.pushButton_face_offre_achat_supprimer.setText(_translate("Form", "Supprimer mon offre", None))
        self.label_txt_face_offre_vente.setText(_translate("Form", "Offres de vente", None))
        self.label_txt_face_offre_vente_prix.setText(_translate("Form", "Faire une offre", None))
        self.pushButton_face_offre_vente_envoyer.setText(_translate("Form", "Envoyer", None))
        self.pushButton_face_offre_vente_accepter.setText(_translate("Form", "Accepter l\'offre", None))
        self.pushButton_face_offre_vente_supprimer.setText(_translate("Form", "Supprimer mon offre", None))
        self.label_face_txt_transactions.setText(_translate("Form", "Transactions", None))

